### ISSUE TITLE
Updating the Xtext Community Website

### ISSUE THREAD

**Issue by miklossy** [eclipse/gemoc-studio-modeldebugging#153]
Hello GEMOC Studio team,

The Xtext team would like to update the [Xtext community website](https://www.eclipse.org/Xtext/community.html) listing all the cool projects people are building around Xtext/Xtend.

See also the corresponding [GitHub issue](https://github.com/eclipse/xtext/issues/1541) and [Bugzilla ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=328477)

If you are interested that the GEMOC Studio project is listed there, please provide the following information as a comment to this issue:

```
<tr>
	<td><a href="project_link">project_name</a></td>
	<td>project_description_max_2_sentences</td>
	<td>license</td>
	<td>category</td>
	<td>author(s)</td>
</tr>

```
We will then update the Xtext community website and get it online as soon as possible.

Thanks!
Tamás

**Comment by dvojtise** [comment]
Hi thanks for offering us the opportunity to be listed there
here is the requested information

```
<tr>
	<td><a href="http://www.eclipse.org/gemoc">Eclipse GEMOC Studio</a></td>
	<td>The GEMOC Studio provides generic components for the development, integration, and use of heterogeneous executable modeling languages. It includes execution trace management,
model animation, advanced debugging, and heterogeneous model coordination services.</td>
	<td>EPL/td>
	<td>Framework</td>
	<td><a href="https://projects.eclipse.org/projects/modeling.gemoc/who">GEMOC contributors</a></td>
</tr>

```

**Comment by miklossy** [comment]
Thank you @dvojtise !

**Comment by miklossy** [comment]
The Eclipse GEMOC Studio project has been added to the [Xtext community website](https://www.eclipse.org/Xtext/community.html).
