### ISSUE TITLE
Trace addon: add option to choose whether the trace should be saved on disk

### ISSUE THREAD

**Issue by ebousse** [eclipse/gemoc-studio-modeldebugging#205]
Currently, the trace addon supposedly always saves its execution trace on disk in the `gemoc-gen` folder (although this is currently not working because of #204 ).

Since there is an overhead when saving the trace, and since one may only need the trace addon for (in-memory) omniscient debugging, an improvement would be to make the trace saving optional, for instance through a boolean option in the addon itself.

**Comment by dvojtise** [comment]
I think we can also have option to save it on-the-fly (ie. on each step, like in #204) or only when the engine is stopped
