### ISSUE TITLE
Move content of commons to dedicated repository

### ISSUE THREAD

**Issue by dvojtise** [eclipse/gemoc-studio-modeldebugging#217]
We now have 2 dedicated repositories [gemoc-studio-commons](https://github.com/eclipse/gemoc-studio-commons) and [gemoc-studio-extras](https://github.com/eclipse/gemoc-studio-extras)

The content that is currently in `gemoc-studio-modeldebugging/commons`  should move to one of these other repo.

Content that is part of the studio or that is used to build the studio should go to  `gemoc-studio-commons`. Extra features that aren't mandatory or that are just helper/convenient features should go to `gemoc-studio-extras`

- [x] Move `gexpressions` to `gemoc-studio-commons`
- [x] Move `commons.eclipse` to `gemoc-studio-commons`
- [x] Move `commons.eclipse.jdt` to `gemoc-studio-commons`
- [x] Move `commons.eclipse.messagingsystem*` to `gemoc-studio-commons`
- [x] Move `commons.eclipse.pde` to `gemoc-studio-commons`
- [x] Move `commons.eclipse.ui` to `gemoc-studio-commons`
- [x] Move `commons.eclipse.xtext` to `gemoc-studio-commons`
- [x] Move `gemoc.dsl*` to `gemoc-studio-commons`
- [x] Move `gemoc.groovy` to `gemoc-studio-commons` (to be discussed if extras or commons ?)
- [x] Move `gemoc.timeline` to `gemoc-studio-commons`
- [x] Move `org.jaxen` to `gemoc-studio-commons`
- [x] Move `org.jdom2` to `gemoc-studio-commons`

- [x] Move `commons.eclipse.jdt.autosrcfolder` to `gemoc-studio-extras`

**Comment by ebousse** [comment]
Just wondering, is gexpressions currently used in the studio?

and where is groovy used? in examples?

**Comment by dvojtise** [comment]
:thinking: You're right, I can find any use of them in the code.

- Groovy is used in some DSL examples, but the only remaining example that use groovy actually embeds it own copy of groovy (https://github.com/eclipse/gemoc-studio-execution-moccml/tree/master/examples/moccmlSigPML/language_workbench/org.eclipse.gemoc.example.moccmlsigpml.groovy) rather than using the version from commons
- as far as I remember gexpressions was used in the concurrent engine, but I can't find where ...
