### ISSUE TITLE
[feature] Declaring options in addons

### ISSUE THREAD

**Issue by ebousse** [eclipse/gemoc-studio-modeldebugging#23]
At the moment, addons can only be _enabled_ or _disabled_.

We should consider giving the possibility to addons to declare _options_ that could then be configured in the launch UI.

This would avoid hard-coded disabled addon features (see https://github.com/eclipse/gemoc-studio-modeldebugging/pull/22)

**Comment by dvojtise** [comment]
Thanks to https://github.com/eclipse/gemoc-studio-modeldebugging/pull/157 it is now possible to declare boolean and string options.

No other type is currently supported (integer, float, enum) but I think this should cover most common use cases.
