### ISSUE TITLE
Animation is refreshed before a step, but not right after?

### ISSUE THREAD

**Issue by ebousse** [eclipse/gemoc-studio-modeldebugging#96]
In the animator we do refresh the diagrams before each execution step, but not *after,* see here: https://github.com/eclipse/gemoc-studio-modeldebugging/blob/243dd4c8e55d7906e12eea128b6689bfe60173cf/framework/execution_framework/plugins/org.eclipse.gemoc.executionframework.extensions.sirius/src/org/eclipse/gemoc/executionframework/extensions/sirius/services/AbstractGemocAnimatorServices.java#L402-L403

Is there a reason for this? If I am correct (and after some testing on my end), this means that with the concurrent engine, when the engine is paused while we are "about to choose" a step, the graphical view was never refreshed after the last step that was executed, which means we always see the model one step earlier than we should.

Was there a reason originally for this choice, maybe performance? If that is the case, then in fact it would be more logical to refresh *after* each step, since chances made to the runtime data only occur in steps (including initialization).

**Comment by dvojtise** [comment]
Actually, there are several issues related to when the Sirius view is refreshed or not #56 #70
Moreover, we don't have any "manual refresh" button that could workaround them.

about your point, I don't remember any real decision. I may be wrong but maybe this is because the "after step" was not present in the early versions of the addon API.

Performance is clearly an issue, especially when we run several steps at once (up to the next breakpoint or full run for example). In addition, maybe we can implement some kind of event stack for refresh action, where we can drop intermediate events (we may lose some intermediate visual effects, but with a faster run)

**Comment by ebousse** [comment]
> Performance is clearly an issue, especially when we run several steps at once (up to the next breakpoint or full run for example). In addition, maybe we can implement some kind of event stack for refresh action, where we can drop intermediate events (we may lose some intermediate visual effects, but with a faster run)

Good point. In fact we could provide an option to not show the animation layer except when paused (or the opposite: an option to show it even when not paused, ie to animate) which would better match the behavior of most PL debuggers where the current instruction is only visible when paused.

**Comment by szschaler** [comment]
But performance wouldn't change by moving the code that's currently in `aboutToExecuteStep` into `stepExecuted`: The same code would still be executed and executed only once. It would now just be executed at a slightly different time.

**Comment by ebousse** [comment]
> But performance wouldn't change by moving the code that's currently in `aboutToExecuteStep` into `stepExecuted`: The same code would still be executed and executed only once. It would now just be executed at a slightly different time.

Correct. I think Didier was simply pointing out that in addition to the current issue we also have an overall problem regarding performance of animations, as each refresh of the Sirius view is costly. I suppose he brought this additional problem out just in case this should be taken into account in the fix.

**Comment by dvojtise** [comment]
> I suppose he brought this additional problem out just in case this should be taken into account in the fix.
exactly :slightly_smiling_face:

**Comment by szschaler** [comment]
So, I've just tried this out, see below:

``` java 
@Override
public void aboutToExecuteStep(IExecutionEngine<?> engine, Step<?> stepToExecute) {
}

@Override
public void stepExecuted(IExecutionEngine<?> engine, Step<?> stepExecuted) {
  if(!(stepExecuted.eContainer() instanceof ParallelStep)){
    activate(engine, stepExecuted);
  }
}
```
 This code starts at line 394 of [AbstractGemocAnimatorServices.java](https://github.com/eclipse/gemoc-studio-modeldebugging/blob/master/framework/execution_framework/plugins/org.eclipse.gemoc.executionframework.extensions.sirius/src/org/eclipse/gemoc/executionframework/extensions/sirius/services/AbstractGemocAnimatorServices.java)

In my tests, it fixes the Sirius update issue without any further problems.

I haven't got write-rights on this repo. Do you need me to create a fork and propose a proper PR from there or could one of you just pick this up?

**Comment by dvojtise** [comment]
yes please, a fork + pull request would simplify the task and integration in the repo :slightly_smiling_face: 

In order to follow Eclipse intellectual property rules please also make sure to 
- add the "Signed-off-by" line in your commits. (option in eclipse git UI, or `-s`on the git command line)
- sign the Eclipse Contributer Agreement in your eclipse account (cf. https://www.eclipse.org/legal/ecafaq.php )
with both using the same email address

**Comment by szschaler** [comment]
Here you go...

**Comment by ebousse** [comment]
Closed by #105

**Comment by dvojtise** [comment]
Actually, after thinking about it again, there are situations where it is interesting to update sirius before calling a step too:


```
def bigStep {
   some_model_changes_1
   innerStep();
   some_model_changes_2
}
def innerStep() {
   some_model_changes_3
}
```

some_model_changes_1 will not be displayed until smallStep() returns  (which migth be long).

I'm planning to reintroduce a notification during the `aboutToExecuteStep` as part of a partial fix for performance issue (https://github.com/eclipse/gemoc-studio-modeldebugging/issues/122)

**Comment by ebousse** [comment]
Well spotted. Indeed we need to refresh in both cases.
